@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Jul 02 15:53:19 +0700 2024
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim PRESENT_DECRYPT_TB_behav -key {Behavioral:sim_1:Functional:PRESENT_DECRYPT_TB} -tclbatch PRESENT_DECRYPT_TB.tcl -log simulate.log"
call xsim  PRESENT_DECRYPT_TB_behav -key {Behavioral:sim_1:Functional:PRESENT_DECRYPT_TB} -tclbatch PRESENT_DECRYPT_TB.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
